title: AncientLanguages
description: AI-powered learning for ancient languages (Classical Greek, Latin, Biblical Hebrew, Aramaic, Akkadian, Sumerian, etc.).
theme: minima
url: https://antonsoo.github.io
baseurl: /AncientLanguages
